### ISSUE TITLE
make install easier

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips-ext#1]
There's a PR for homebrew here:

https://github.com/Homebrew/homebrew-php/pull/3757

It seems they probably won't allow it until this extension becomes better-known.

I've applied for a PECL account here:

http://marc.info/?l=pecl-dev&m=147877795520881&w=2

**Comment by jcupitt** [comment]
OK, we have a pecl package!

https://pecl.php.net/package/vips

It'll probably need some work for Windows

**Comment by rexxars** [comment]
Do you know if there are any Ubuntu repositories that include libvips >= 8.3?

**Comment by jcupitt** [comment]
Hi, yes, 16.10 is on 8.3.3, or it's a simple package to build yourself.

**Comment by jcupitt** [comment]
I'll make a separate issue for Windows support.
