### ISSUE TITLE
new_from_memory / write_to_memory

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/php-vips-ext#12]
It would be nice to wrap an image around a memory array or to write an image to a large memory array. This can be useful for moving images between libvips and imagemagick or to calculate the perceptual hash of an image (see below).

The new functions can be named like this:
Extension: `new_from_memory`, `write_to_memory`.
php-vips: `Image::newFromMemory`, `->writeToMemory`.

I can open a PR at the php layer to support these new functions if this has been implemented in the extension.

If you are wondering why I need this:
For our test cases we are calculating the perceptual hash of an image (based on the [dHash algorithm](http://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html)) to verify the similarity of expected vs actual images (using a distance threshold). It looks like [this](https://gist.github.com/kleisauke/ccdeb238af6c155aa42048de0132679d) (so `->copyMemory` and `->getpoint` are the important ones). If there's a `->writeToMemory` function it could be somewhat [optimized](
https://gist.github.com/kleisauke/7c43c2a265780ad6ac08727f52a6ffeb).

**Comment by jcupitt** [comment]
Sure, this is a great idea! Are you OK doing this? I'm working on a JS binding now and I ought to get that done before I switch languages again.

dHash is rather old, fwiw, I know it from the 1980s and it's probably older than that. I would do it slightly differently: shrink to 8x8 greyscale, find image average, then set bits depending on whether the pixel is brighter or darker than the image average. 

This has the same independence from brightness property you get with the difference image, but saves you computing left-right differences. You can also look at the images and guess what they represent, which you can't with a left-right diff.

**Comment by kleisauke** [comment]
I'm OK with implementing this. You can expect a pull request on the weekend. 

Wow, I didn't know that dHash already existed since 1980s. Your hash calculation sounds like an [average hash](http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html). I tried to implement [this](https://gist.github.com/kleisauke/80c71acc010688b9dc40cb08d0accb54) and it seems not to work for sequential access. (I think this is fixable when there is a `->writeToMemory` function, or when doing a `->linecache`).

By the way,
You're doing a great job with those (new) FFI bindings for libvips! I'm happy to test the Node.js binding (on several environments) when you're ready. Perhaps sharp can also benefit from node-vips in the near future, https://github.com/lovell/sharp/issues/241 is relevant here.

**Comment by jcupitt** [comment]
Oh heh yes, I described aHash. I suppose dHash is a little better for non-linear lightness changes.

**Comment by jcupitt** [comment]
I think this is all done now, I'll close and update pecl.

Good job!
