### ISSUE TITLE
Expose Vips library version to PHP

### ISSUE THREAD

**Issue by chregu** [jcupitt/php-vips-ext#14]
It would be useful to know which vips library version is used, so that the user can be warned, in case it's not the correct one with features missing. I see that there's the vips_version() function in vips, but I couldn't figure out, how to access that from PHP.

Something like

```
PHP_FUNCTION(vips_version) {
  char digits[256];
  vips_snprintf(digits, 256, "%d.%d.%d", vips_version(0), vips_version(1), vips_version(2));
  RETVAL_STRING(strdup(digits))
}
```

would maybe do it already (my PHP C know how is too rusty, but I can give it a try, if it's not already accessible through other means)

**Comment by jcupitt** [comment]
Hello again, this is in the info table, would that be enough?

```
$ php -i
vips

vips property => value
Major version => 8
Minor version => 6
Micro version => 0
SIMD support with liborc => yes
JPEG support => yes
PNG support => yes
TIFF support => yes
GIF support => yes
OpenEXR support => yes
load OpenSlide => yes
load Matlab => yes
load PDF => yes
load SVG => yes
FITS support => yes
WebP support => yes
load with libMagick => yes
Text rendering support => yes
ICC profile support with lcms => yes
```
Otherwise, you're right, we'd need to add another API call to `vips.c`.

**Comment by chregu** [comment]
Unfortunately phpinfo() is not enough, I use for example `composite` in my publicly available class (it's now here https://github.com/rokka-io/imagine-vips ) and i'd like to throw an informative exception, if the vips version isn't 8.6 yet. Or maybe in other cases fall back to an older way to do things (eg rotate with affinity we discussed). So a `vips_version` function would be great to have.

**Comment by chregu** [comment]
made an MR in #15. Hopefully I did it right

**Comment by jcupitt** [comment]
OK, all done, I'll close.
