### ISSUE TITLE
Suppress VIPS-WARNING output?

### ISSUE THREAD

**Issue by chregu** [jcupitt/php-vips-ext#20]
When I try to get certain images (can reproduce it with CMYK images) as tiff, I get a 
```
(banana:11322): VIPS-WARNING **: rounding up IPCT data length
```
on the console. The warning itself is fine in this case, we don't care much about IPCT data at that point. But the output of the Warning is kinda ugly and distracting. Is there any way to suppress it? The PHP way with the @ in front doesn't work.

**Comment by jcupitt** [comment]
Hi Christian, define the environment variable `VIPS_WARNING` to hide warning messages.

Background -- libvips uses g_log for messages:

https://developer.gnome.org/glib/stable/glib-Message-Logging.html

So to capture messages, you define a log handler for the VIPS domain set at WARNING level, something like:

```C
    g_log_set_handler( "VIPS", G_LOG_LEVEL_WARNING, my_log_handler, NULL );
```

This is awkward and annoying from things like PHP, so the `VIPS_WARNING` environment handler is a workaround for these cases.

**Comment by chregu** [comment]
Ok, thanks for the answer

**Comment by jcupitt** [comment]
... of course, that will hide all warning messages, which maybe you don't want.
