### ISSUE TITLE
Minimum libvips version set to 8.3

### ISSUE THREAD

**Issue by marhub** [jcupitt/php-vips-ext#4]
https://github.com/jcupitt/php-vips-ext/blob/master/config.m4#L7

This is on purpose ? 
I have libvips 8.2 ( ubuntu 16.04, and currently can't update to 16.10 which has libvips in 8.3 ).

Changed that const to 8.2, recompiled, and it seems to be working.

**Comment by jcupitt** [comment]
I agree, 8.2 seems to pass all tests. I tried 8.1, but that fails one. 

I'll delay updating pecl again in case something else comes up in the next day or two, this seems like a relatively minor change.

Thanks!

**Comment by jcupitt** [comment]
I meant to say, I think the 8.3 was just because that was the current version when I started php-vips-ext, and I didn't want to explicitly support older libvipses.

**Comment by marhub** [comment]
Great!

**Comment by jcupitt** [comment]
OK, done! I'll close.
