### ISSUE TITLE
Async vips_call()

### ISSUE THREAD

**Issue by uasan** [jcupitt/php-vips-ext#8]
Hi.
Can `vips_call` work asynchronously?

```PHP
<?php

vips_call($cmd, $args, function($result){
// callback completion
}) 

```
Thank.

P.S.
We use PHP cli script daemon mode, `libuv` as EventLoop.

**Comment by jcupitt** [comment]
Hello, that's an interesting idea. It's certainly threaded, so it should work. The node.js libvips binding is async.

You'd need to write a little wrapper to do async dispatch I suppose, but I've never looked into it. You'd need to ask a PHP expert.

**Comment by uasan** [comment]
Working example using thread pool from libuv.

Required: PHP 7, ZTS and php-uv module.
pecl install uv
http://pecl.php.net/package/uv

```PHP
<?php

$loop  = uv_default_loop();

$thread = function()
{
	echo "THREAD-CALL\n";

	$opt =
	[
		'height'      => 1920,
		'size'        => 2,
		'auto_rotate' => 1,
		'crop'        => 0,
		'linear'      => 0
	];

	$img = vips_call('thumbnail', null, '/opt/exif.jpg', 1920, $opt)['out']?? null;

	if($img === null)
	{
		echo vips_error_buffer()."\n";
	}
	else
	{
		vips_image_write_to_file($img, '/var/www/thumbnail.jpg');
	}
};

$after = function()
{
	echo "THREAD-CALL-AFTER\n";
};

for($i = 0; $i < 4; $i++)
{
	uv_queue_work($loop, $thread, $after);
}

uv_run($loop);
```

**Comment by jcupitt** [comment]
Woah, nice job!

**Comment by uasan** [comment]
PHP ZTS thread pool from libuv, often segmentation crash :(

We used GraphicsMagick, as worker, send to STDIN
http://www.graphicsmagick.org/batch.html

Run (spawn child process)
`gm batch -`

Write to STDIN
`
convert big.jpg -format "%w %h %[exif:DateTime]" -write info:- -strip -resize "250x250>" small.jpg\n
`

Read from STDOUT
```800 600 2015-06-12\n```

It is safely and works quickly, one worker process `gm`, executing requests the pipeline mode from STDIN, in `vips_tools` such prog there is? :)

Thank.

**Comment by jcupitt** [comment]
Yes, vips has `vipsthumbnail`, a command-line resizer. It's file operations only though, so you'd need to go via the filesystem. 

We should be able to get the libuv one working though, I wonder what the issue is. I'll see if I can reproduce it here.

**Comment by uasan** [comment]
I looked at vips lua, I can write lua script, use as child PHP process
```PHP
$work = Worker::spawn('luajit my_script.lua');
$work->write('...'); // write to STDIN script.lua
```

**Comment by jcupitt** [comment]
I'm working on vips-lua at the moment, it's not finished yet. Another week or two.

You could write a php script and call that as a child process, that would be a simple solution. 

libvips is used with libuv in node.js with very large deployments (tumblr, etc.) and it works fine, so I think the crashes you are seeing must just be problems with php-vips-ext. I suppose we must add some locks to this file:

https://github.com/jcupitt/php-vips-ext/blob/master/vips.c

Do you know what the rules are for what calls need locks? Is there a document I can read?

**Comment by jcupitt** [comment]
Do you know lua well? If you do, some help on lua-vips would be very welcome. I'm not a lua expert at all, and it would be wonderful if someone who knew what they were doing could check it for dumbness.

**Comment by uasan** [comment]
> Do you know what the rules are for what calls need locks? Is there a document I can read?

I'm not an expert in multithreading, my experiments showed that PHP ZTS and libuv without Vips, segmentation error, so I abandoned this idea.

Crashing main PHP process is not allowed, our main PHP process is engaged in important business logic.

> Do you know lua well? If you do, some help on lua-vips would be very welcome. I'm not a lua expert at all, and it would be wonderful if someone who knew what they were doing could check it for dumbness.

I wrote my first script on lua yesterday, I'm learning :)

**Comment by uasan** [comment]
I resolve the cause, this problem in php-ext-raphf is thread not safe, without it everything works well.

**Comment by jcupitt** [comment]
Good news! I'll close.
